#!/bin/sh
APP_NAME=reloadevery.xpi
rm ${APP_NAME}
find . -name "*.xul" -print | zip ${APP_NAME} -@
find . -name "*.js" -print | zip ${APP_NAME} -@
find . -name "*.dtd" -print | zip ${APP_NAME} -@
find . -name "*.png" -print | zip ${APP_NAME} -@

zip ${APP_NAME} chrome.manifest install.rdf

